"""add sla_records and notifications tables, migrate sla_config to jsonb

Revision ID: 40164b94b52f
Revises: 6a1b2c3d4e5f
Create Date: 2026-08-09 16:17:43.666086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40164b94b52f'
down_revision: Union[str, None] = '6a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index('ix_notifications_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_read = false'))
    op.create_table('sla_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('first_resp_hours', sa.Integer(), nullable=False),
    sa.Column('resolution_hours', sa.Integer(), nullable=False),
    sa.Column('first_resp_due', sa.DateTime(), nullable=False),
    sa.Column('resolution_due', sa.DateTime(), nullable=False),
    sa.Column('first_resp_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('first_resp_breached', sa.Boolean(), nullable=False),
    sa.Column('resolution_breached', sa.Boolean(), nullable=False),
    sa.Column('first_resp_warned_agent_3h', sa.Boolean(), nullable=False),
    sa.Column('first_resp_warned_agent_2h', sa.Boolean(), nullable=False),
    sa.Column('first_resp_warned_supervisor_1h', sa.Boolean(), nullable=False),
    sa.Column('resolution_warned_agent_3h', sa.Boolean(), nullable=False),
    sa.Column('resolution_warned_agent_2h', sa.Boolean(), nullable=False),
    sa.Column('resolution_warned_supervisor_1h', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_index(op.f('ix_sla_records_id'), 'sla_records', ['id'], unique=False)
    op.create_index('ix_sla_records_first_resp_active', 'sla_records', ['first_resp_due'], unique=False, postgresql_where=sa.text('first_resp_at IS NULL'))
    op.create_index('ix_sla_records_resolution_active', 'sla_records', ['resolution_due'], unique=False, postgresql_where=sa.text('resolved_at IS NULL'))

    # Migrate categories.sla_config from JSON to JSONB
    op.alter_column('categories', 'sla_config',
                    existing_type=sa.JSON(),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=False,
                    postgresql_using='sla_config::jsonb')

    # Data migration: flat sla_config -> nested per-priority format
    op.execute("""
        UPDATE categories
        SET sla_config = jsonb_build_object(
            'P0', sla_config,
            'P1', sla_config,
            'P2', sla_config,
            'P3', sla_config
        )
        WHERE sla_config ? 'first_resp_hours' AND NOT sla_config ? 'P0'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'sla_config',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    type_=sa.JSON(),
                    existing_nullable=False,
                    postgresql_using='sla_config::json')

    op.drop_index('ix_sla_records_resolution_active', table_name='sla_records')
    op.drop_index('ix_sla_records_first_resp_active', table_name='sla_records')
    op.drop_index(op.f('ix_sla_records_id'), table_name='sla_records')
    op.drop_table('sla_records')
    op.drop_index('ix_notifications_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
