"""add email webhook models

Revision ID: 6a1b2c3d4e5f
Revises: e71bb5d3a9f0
Create Date: 2026-08-09 02:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1b2c3d4e5f'
down_revision: Union[str, None] = 'e71bb5d3a9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_ingestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_email', sa.String(length=100), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('in_reply_to', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_email_ingestions_id'), 'email_ingestions', ['id'], unique=False)
    op.create_index(op.f('ix_email_ingestions_message_id'), 'email_ingestions', ['message_id'], unique=True)
    op.create_index(op.f('ix_email_ingestions_sender_email'), 'email_ingestions', ['sender_email'], unique=False)
    op.add_column('ticket_replies', sa.Column('email_message_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_ticket_replies_email_message_id'), 'ticket_replies', ['email_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_replies_email_message_id'), table_name='ticket_replies')
    op.drop_column('ticket_replies', 'email_message_id')
    op.drop_index(op.f('ix_email_ingestions_sender_email'), table_name='email_ingestions')
    op.drop_index(op.f('ix_email_ingestions_message_id'), table_name='email_ingestions')
    op.drop_index(op.f('ix_email_ingestions_id'), table_name='email_ingestions')
    op.drop_table('email_ingestions')
    # ### end Alembic commands ###
